<a href="https://colab.research.google.com/github/aryaniyaps/learning_numpy/blob/main/learning_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic array operations**

In [ ]:
import numpy as np

In [5]:
# create a simple array
my_arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

In [7]:
# array dimensions
print(my_arr.ndim)

# array shape
print(my_arr.shape)

# array size
print(my_arr.size)

# array datatype
# (arrays can only have one datatype)
print(my_arr.dtype)

# array item size
# (size of every item in array)
print(my_arr.itemsize)

# array data (won't be accessed normally)
print(my_arr.data)

# check type of array
print(type(my_arr))

2
(2, 4)
8
int64
8
<class 'numpy.ndarray'>


In [9]:
# explicitly set the datatype during array creation
explicit_dtype_array = np.array([[1,2], [3,4]], dtype=complex)
explicit_dtype_array

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [13]:
# fill array full of zeros
zero_arr = np.zeros((3, 4))
print(zero_arr)

# fill array with ones
one_arr = np.ones((3, 4))
print(one_arr)

# fill array with random values initially
empty_arr = np.empty((3, 4))
print(empty_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Creating sequences of numbers**

analogous to the builtin `range` function in Python.

In [15]:
my_arr = np.arange(10, 100, 5)
print(my_arr)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [18]:
# generate evenly spaced numbers over a specified interval
print(np.linspace(2.0, 3.0, num=5))

[2.   2.25 2.5  2.75 3.  ]


**Fill up arrays with values based on a given shape**

In [17]:
reference_arr = np.array([1, 2, 3])

# fill up with zeros in a similar shape
print(np.zeros_like(reference_arr))

# fill up with ones in a similar shape
print(np.ones_like(reference_arr))

# create a random array with similar shape
print(np.empty_like(reference_arr))

[0 0 0]
[1 1 1]
[1 1 1]


**Operations on arrays**

operations are carried out on arrays element-wise.

*binary operations*

In [19]:
arr_1 = np.array([1, 2, 3, 4])
arr_2 = np.array([5, 6, 7, 8])

print("1 - 2: ", arr_1 - arr_2)
print("1 + 2: ", arr_1 + arr_2)
print("1**2 ", arr_1 ** 2)
print("1 < 2: ", arr_1 < arr_2)
print("1 > 2: ", arr_1 > arr_2)
print("1 * 2: ", arr_1 * arr_2)

1 - 2:  [-4 -4 -4 -4]
1 + 2:  [ 6  8 10 12]
1**2  [ 1  4  9 16]
1 < 2:  [ True  True  True  True]
1 > 2:  [False False False False]
1 * 2:  [ 5 12 21 32]


*unary operations*

In [20]:
print("sum: ", arr_1.sum())
print("max: ", arr_1.max())
print("min: ", arr_1.min())

sum:  10
max:  4
min:  1


**reshaping arrays**

In [22]:
linear_arr = np.arange(12)
print("linear array: ", linear_arr)
print("reshaped array: ", linear_arr.reshape(3, 4))

linear array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
